.\" This document is in the public domain.
.\" vim: fdm=marker
.
.\" FRONT MATTER {{{
.Dd Aug 26, 2014
.Os
.Dt GIT-MAILZ 1
.
.Sh NAME
.Nm git-mailz
.Nd Send a collection of patches as emails
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h | \-help
.Nm
.Op Fl f Ar ENVELOPE-SENDER
.Bro Ar FILE | DIRECTORY Brc Ns \&...
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
Feeds patches given on the command line to
.Xr sendmail 1 .
Arguments can name individual patch files or directories,
and are expected to be complete email messages.
Recipients and sender are picked up from headers.
.Ss Options
.Bl -tag -width "xxx"
. It Fl h
Display usage information.
. It Fl \-help
Display man page.
. It Fl f Ar ENVELOPE-SENDER
Invoke
. Va mailz.sendmail
with
. Fl f Ar ENVELOPE-SENDER .
.El
.
.Ss Configuration
.Bd -literal
[mailz]
  sender = ENVELOPE-SENDER
  sendmail = EXE
.Ed
.Bl -tag -width "xxx"
. It mailz.sender
Invoke
. Va mailz.sendmail
with
. Fl f Ar ENVELOPE-SENDER .
. It mailz.sendmail
Feed patches to
. Va EXE .
Defaults to
. Pa /usr/sbin/sendmail .
.El
.\" DESCRIPTION }}}
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Bl -tag -width xxx
.It Ev GIT_MAILZ_SENDER
Override
.Va mailz.sender
configuration.
.It Ev GIT_MAILZ_SENDMAIL
Override
.Va mailz.sendmail
configuration.
.El
.Pp
.Nm
is implemented in terms of third-party commands
which
use environment variables.
This means
.Nm
may be influenced by environment variables used by
.Xr git 1  ,
.Xr zsh 1 ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.Sh FILES
.Nm
uses
.Xr git-config 1
to retrieve configuration settings.
.\" FILES }}}
.\" EXAMPLES {{{
.\"Sh EXAMPLES
.\" EXAMPLES }}}
.\" DIAGNOSTICS {{{
.Sh DIAGNOSTICS
.Ex -std
.\" DIAGNOSTICS }}}
.\" SEE ALSO {{{
.Sh SEE ALSO
.Bl
.It
.Xr git-format-patch 1 ,
.Xr git-send-email 1 ,
.Xr sendmail 1 ,
.Xr sendmail 8 .
.El
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.An Roman Neuhauser Aq Mt neuhauser+git-mailz@sigpipe.cz
.Lk https://github.com/roman-neuhauser/git-mailz/
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Lk https://github.com/roman-neuhauser/git-mailz/issues
.\" BUGS }}}
